name: darknote
description: Un editor de texto ultraligero y funcional con tema oscuro.
publish_to: 'none'
version: 1.0.0+5

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Versión exacta para evitar errores de API
  file_picker: 5.3.1
  path_provider: 2.1.2
  permission_handler: 11.3.0
  shared_preferences: 2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 3.0.1

flutter:
  uses-material-design: true
